# Generated by Django 2.2.11 on 2020-03-08 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catelogy',
            name='id_product',
        ),
        migrations.AddField(
            model_name='product',
            name='id_catelogy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Catelogy'),
        ),
    ]
